-- Close privileged RPC, profile-mutation, and answer-key exposure paths found
-- during the August 2026 security review. Browser roles receive only the
-- minimum grants needed by the application; trusted scoring stays server-only.

-- Internal progression helpers run only as part of the service-only atomic
-- submission function. They are not public API endpoints.
REVOKE ALL ON FUNCTION public.upsert_skill_progress(uuid, uuid, uuid, integer, integer)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.award_chapter_badge_if_earned(uuid)
  FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.submit_exercise_attempt(uuid, uuid, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_exercise_attempt(uuid, uuid, jsonb)
  TO service_role;

-- A signed-in user may change only their display name. Identity, role, and
-- account-control fields are service-only even if a future grant is widened by
-- mistake; the trigger provides a second independent enforcement layer.
CREATE OR REPLACE FUNCTION public.guard_profiles_role()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
  IF auth.uid() IS NOT NULL AND (
    NEW.id IS DISTINCT FROM OLD.id
    OR NEW.email IS DISTINCT FROM OLD.email
    OR NEW.role IS DISTINCT FROM OLD.role
    OR NEW.created_at IS DISTINCT FROM OLD.created_at
    OR NEW.disabled_at IS DISTINCT FROM OLD.disabled_at
    OR NEW.disabled_by IS DISTINCT FROM OLD.disabled_by
  ) THEN
    RAISE EXCEPTION 'protected_profile_field';
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.guard_profiles_role()
  FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL PRIVILEGES ON TABLE public.profiles
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.profiles TO authenticated;
GRANT UPDATE (display_name) ON TABLE public.profiles TO authenticated;

-- Question rows include canonical answers and, for word-sort games, answer
-- mappings inside metadata. No browser database role may read the base table.
-- Authenticated Server Components use the service key only after checking the
-- pupil, enrolment, exercise, and chapter lock.
REVOKE ALL PRIVILEGES ON TABLE public.exercise_questions
  FROM PUBLIC, anon, authenticated;

-- Cryptographically generate class codes. 32 symbols divide 256 evenly, so
-- selecting each byte modulo 32 introduces no distribution bias.
CREATE OR REPLACE FUNCTION public.generate_join_code()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  candidate text;
  bytes bytea;
  attempt integer := 0;
  i integer;
BEGIN
  LOOP
    bytes := extensions.gen_random_bytes(10);
    candidate := '';
    FOR i IN 0..9 LOOP
      candidate := candidate || substr(alphabet, (get_byte(bytes, i) % 32) + 1, 1);
    END LOOP;

    IF NOT EXISTS (SELECT 1 FROM public.classes WHERE join_code = candidate) THEN
      RETURN candidate;
    END IF;

    attempt := attempt + 1;
    IF attempt > 20 THEN
      RAISE EXCEPTION 'Could not allocate a unique join code';
    END IF;
  END LOOP;
END;
$function$;

REVOKE ALL ON FUNCTION public.generate_join_code()
  FROM PUBLIC, anon, authenticated, service_role;

-- Durable, per-pupil throttling for answer checks and final submissions. The
-- table is private and the public wrapper is callable only by the service role.
CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS private.exercise_rate_limit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action text NOT NULL CHECK (action IN ('check', 'submit')),
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS exercise_rate_limit_events_lookup_idx
  ON private.exercise_rate_limit_events (student_id, action, occurred_at DESC);

ALTER TABLE private.exercise_rate_limit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE private.exercise_rate_limit_events
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON SEQUENCE private.exercise_rate_limit_events_id_seq
  FROM PUBLIC, anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.consume_exercise_rate_limit(
  p_student uuid,
  p_action text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, private
AS $function$
DECLARE
  v_limit integer;
  v_count integer;
BEGIN
  IF p_student IS NULL OR p_action NOT IN ('check', 'submit') THEN
    RETURN false;
  END IF;

  v_limit := CASE p_action WHEN 'check' THEN 60 ELSE 12 END;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_student::text || ':' || p_action, 0));

  DELETE FROM private.exercise_rate_limit_events
   WHERE student_id = p_student
     AND occurred_at < now() - interval '1 day';

  SELECT count(*)
    INTO v_count
    FROM private.exercise_rate_limit_events
   WHERE student_id = p_student
     AND action = p_action
     AND occurred_at >= now() - interval '1 minute';

  IF v_count >= v_limit THEN
    RETURN false;
  END IF;

  INSERT INTO private.exercise_rate_limit_events (student_id, action)
  VALUES (p_student, p_action);
  RETURN true;
END;
$function$;

REVOKE ALL ON FUNCTION public.consume_exercise_rate_limit(uuid, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_exercise_rate_limit(uuid, text)
  TO service_role;

-- Password recovery is now a one-time link and is included in the existing
-- administrator audit trail.
ALTER TABLE public.teacher_account_audit
  DROP CONSTRAINT IF EXISTS teacher_account_audit_action_check;
ALTER TABLE public.teacher_account_audit
  ADD CONSTRAINT teacher_account_audit_action_check
  CHECK (action IN ('disable', 'restore', 'remove', 'reset_mfa', 'reset_password'));
